dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - release-0.9
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "9"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo bash tools/setup/install_geth_1_8_3.sh
  - geth version
install:
  - npm install
  - npm install -g mocha
before_script:
script:
  - export OPENST_PLATFORM_PATH=$(pwd)
  - export OST_DEBUG_ENABLED=1
  - node tools/setup/index.js
  - source $HOME/openst-setup/openst_env_vars.sh
  - nohup node tools/setup/start_services.js </dev/null >/dev/null 2>&1 &
  - sleep 120
  - source $HOME/openst-setup/openst_env_vars.sh
  - node tools/setup/branded_token/register.js "ACME Coin" "ACME" 500000000000000000000
  - node tools/setup/branded_token/mint.js "ACME" 500000000000000000000
  - npm run unit_test
  - npm run integration_test
after_script:
  - kill $(ps aux | grep 'tools/setup/start_services.js' | awk '{print $2}')