dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - release-0.9
  - feature/config_strategy
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "9"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo bash tools/setup/install_geth_1_8_3.sh
  - geth version
install:
  - npm install
  - npm install -g mocha
before_script:
  - mkdir -p dynamodb
  - export AUTO_SCALE_DYNAMO=0
  - export OS_CACHING_ENGINE=none
  - wget https://s3.ap-south-1.amazonaws.com/dynamodb-local-mumbai/dynamodb_local_latest.zip -O ./dynamodb/dynamodb_local_latest.zip
  - unzip ./dynamodb/dynamodb_local_latest.zip
  - nohup java -Djava.library.path=./dynamodb/DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &
  - sleep 30
script:
  - export OPENST_PLATFORM_PATH=$(pwd)
  - export OST_DEBUG_ENABLED=1
  - node tools/setup/index.js -s all </dev/null >/dev/null 2>&1 &
  - sleep 60
  - source $HOME/openst-setup/openst_env_vars.sh
  - nohup node tools/setup/start_value_services.js
  - sleep 30
  - nohup node tools/setup/start_utility_services.js ~/openst-setup/bin/utility-chain-1000/openst_platform_config.json
  - sleep 120
  - source $HOME/openst-setup/openst_env_vars.sh
  - node tools/setup/branded_token/register.js "ACME Coin" "ACME" 10
  - sleep 30
  - node tools/setup/branded_token/mint.js "ACME" 1000000000000000000000
  - sleep 30
  - mocha --timeout 120000 test/* --exit
after_script:
  - kill $(ps aux | grep 'tools/setup/start_services.js' | awk '{print $2}')
  - kill $(ps aux | grep 'DynamoDBLocal.jar' | awk '{print $2}')
  - rm -rf dynamodb